#!/bin/bash
# Author: Davide Marchegiani
PROGNAME=$0

usage() {
  cat << EOF
Usage: $PROGNAME [-i <tot_iter>] [-n <tsurf>] ...

Possible keys:
-c -> correction coefficient (default 0.3)
-o -> change clouds only over oceans
-i -> total number of iterations (default 20)
-n -> 0th iteration new tsurf pattern 
-w <working directory> -> "Path to be set as working directory for the run"

EOF
  exit 1
}

while getopts hi:n:o:c:w: opt; do
  case $opt in
    c) corr=$OPTARG;;
    o) ocean_flag="_ocean";;
    i) tot_iter=$OPTARG;;
    n) tsurf=$(readlink -m $OPTARG);;
    w) working_dir=$(realpath $OPTARG);;
    (*) usage
  esac
done


working_dir=${working_dir:=/Users/dmar0022/university/phd/greb-official/work} 
((${tot_iter:=20}))
if ! [ -z ${ocean_flag+x} ]; then o="-o"; else o=""; fi
# Files for 1st iteration
tsurf=${tsurf:="/Users/dmar0022/university/phd/greb-official/output/scenario.exp-930.geoeng.2xCO2.cld.artificial.frominput_x1.1_50yrs"}
corr=${corr:=0.3}
tsurf_init=$tsurf
sim_years=${tsurf##*_};sim_years=${sim_years%.*}

cloud_folder=/Users/dmar0022/university/phd/greb-official/artificial_clouds/cld.artificial.iteration${ocean_flag}_${corr}corr
# Initialize iterations
niter=1
while (( $niter <= $tot_iter )); do
    cloud_name=cld.artificial.iter${niter}${ocean_flag}_${corr}corr
    # Create cloud matrix
    echo -e "\nIter. ${niter}/${tot_iter} -- Creating new cloud matrix..."
    python cloud_iteration_process.py -c $corr --it $niter -t $tsurf $o
    pad="Iter. ${niter}/${tot_iter} "
    # RUN GREB

    printf "%*s%b" ${#pad} '' "-- Run GREB\n"
    ./myjobscript.bash -e 930 -y ${sim_years%yrs} -c $cloud_folder/$cloud_name -w $working_dir
    # Change files for next iteration
    tsurf=/Users/dmar0022/university/phd/greb-official/output/scenario.exp-930.geoeng.2xCO2.cld.artificial.iter${niter}${ocean_flag}_${corr}corr_${sim_years}
    ((niter++))
done
echo -e "\nPlotting iterations...\n"
python ./plot_iter.py -i $tsurf_init -c $corr -f 'cloud' -e 930 $o
echo -e "DONE!!\n"
exit
